### ISSUE TITLE
Specification mismatch in decipher algorithm

### ISSUE THREAD

**Issue by mojtaba-bisheh** [secworks/aes#10]
FYI, [Lubis](https://github.com/ludwigatlubis) (@ludwigatlubis) is doing FPV to verify the AES right now and they found a bug according to the [NIST specification](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.197.pdf).

Module that contains the bug:
[src/rtl/aes_decipher_block.v](https://github.com/secworks/aes/blob/master/src/rtl/aes_decipher_block.v)

The bug is in line 326 invs_shift_rows_block() function should not get executed in the init_update state, as it is repeated in the next state again.

Reproduce the bug:
A simple formal assertion shows the bug. 

Solution:
Removing that line fixes the bug.

We are working on it here: https://github.com/chipsalliance/caliptra-rtl/issues/165

**Comment by secworks** [comment]
First - thanks for bringing this to my attention! I greatly appreciate any results, feedback from your work.
I'll take a look on the issue.

**Comment by secworks** [comment]
@mojtaba-bisheh Since this was closed for https://github.com/chipsalliance/caliptra-rtl/issues/165 should we close it here too?

**Comment by mojtaba-bisheh** [comment]
@secworks Thanks for checking. Yes, there was not any bug in this block.
