### ISSUE TITLE
Add simple description of usage

### ISSUE THREAD

**Issue by secworks** [secworks/aes#4]
Add a simple description of how the core is to be used to the README.md
Something like:
    1. Load the key to be used by writing to the key register words.
    2. Set the key length by writing to the config register.
    3. Initialize key expansion by writing a one to the init bit in the control register.
    4. Wait for the ready bit in the status register to be cleared and then to be set again. This means that the key expansion has been completed.
    5. Write the cleartext block to the block registers.
    6. Start block processing by writing a one to the next bit in the control register.
    7. Wait for the ready bit in the status register to be cleared and then to be set again. This means that the data block has been processed.
    8. Read out the ciphertext block from the result registers.

**Comment by mickey20111111** [comment]
Dear Joachim Strömbergson
Why does not support AES-192?
Can you improve the project and add  AES-192 feature
Thank you !
Best Regards
Mickey
From: Joachim Strömbergson 
Sent: Friday, February 22, 2019 2:14 AM
To: secworks/aes 
Cc: Subscribed 
Subject: [secworks/aes] Add simple description of usage (#4)

1. Load the key to be used by writing to the key register words.

2. Set the key length by writing to the config register.

3. Initialize key expansion by writing a one to the init bit in the control register.

4. Wait for the ready bit in the status register to be cleared and then to be set again. This means that the key expansion has been completed.

5. Write the cleartext block to the block registers.

6. Start block processing by writing a one to the next bit in the control register.

7. Wait for the ready bit in the status register to be cleared and then to be set again. This means that the data block has been processed.

8. Read out the ciphertext block from the result registers.

**Comment by secworks** [comment]
Hi!

Thanks for the question. The reason for not supporting AES-192 is that in my experience, AES-192 is very rarely used in any applications ans use cases. Either AES-128 or AES-256 is being used. There difference in performance, key length etc is so small between AES-192 and AES-256 that if you need more than AES-128, AES-256 is what is used.

Adding AES-192 would primarily complicate the key expansion. If someone would create a patch (with updates for test cases etc) for it, I would be happy to add support for AES-192.

**Comment by secworks** [comment]
Added the sequence in https://github.com/secworks/aes/commit/11b8919c95489ce8bab2968da909cad7e759db21
