### ISSUE TITLE
Fix CI build for skywater using edalize

### ISSUE THREAD

**Issue by secworks** [secworks/aes#9]
It seems the edalize based CI build for skywater is broken (again):

`Error: : during executing openroad script /openlane/scripts/openroad/groute.tcl
Error: : Exit code: 1
Error: : Last 10 lines:

ERROR: Unable to find image 'edalize/openlane-sky130:mpw4' locally

...
...

Status: Downloaded newer image for edalize/openlane-sky130:mpw4
no such variable
    (read trace on "::env(PWD)")
    invoked from within
"relpath $::env(PWD) $reproducible_dir"
    (procedure "run_openroad_script" line 38)
    invoked from within
"run_openroad_script $::env(SCRIPTS_DIR)/openroad/groute.tcl -indexed_log $saveLOG"
    (procedure "global_routing_fastroute" line 5)
    invoked from within
"global_routing_fastroute"
    (procedure "global_routing" line 13)
    invoked from within
"global_routing"
    (procedure "run_routing" line 35)
    invoked from within
"run_routing"
    (procedure "run_routing_step" line 7)
    invoked from within
"[lindex $step_exe 0] [lindex $step_exe 1] "
    (procedure "run_non_interactive_mode" line 54)
    invoked from within
"run_non_interactive_mode {*}$argv"
    invoked from within
"if { [info exists flags_map(-interactive)] || [info exists flags_map(-it)] } {
	puts_info "Running interactively"
	if { [info exists arg_values(-file)..."
    (file "/openlane/flow.tcl" line 346)
make: *** [Makefile:4: all] Error 1

ERROR: Failed to build secworks:crypto:aes:0 : '['make']' exited with an error: 2

Error: Process completed with exit code 1.
`

Any idea what the error is @olofk ?

**Comment by olofk** [comment]
Ok, so after reading through almost 40000 lines of the build log, I found the error at line 39992 `[ERROR GRT-0229] Vertical edge usage exceeds the maximum allowed.` OpenLANE simply fails to route the design.

You could try changing the utilization ratio, target clock frequency or something to see if it disappears. Or perhaps some code changes caused this? I also see a ton of timing errors related to reset, so maybe the router is trying really hard to meet timing there.

We should probably also use a newer version of OpenLANE, but I haven't had time to package one for a long time

**Comment by secworks** [comment]
Wow! Quite unexpected. Since the core hasn't fundamentally changed, and I nowadays have the same openlane build issue with most/all cores, I assumed that the environment have regressed somehow. Not that the design suddenly would start really being the issue.

**Comment by secworks** [comment]
So this has nothing to do with the problem?
`ERROR: Unable to find image 'edalize/openlane-sky130:mpw4' locally
...
...
Status: Downloaded newer image for edalize/openlane-sky130:mpw4`

**Comment by olofk** [comment]
No. It just hasn't got the docker image cached and needs to download it

**Comment by secworks** [comment]
Ah, ok.
